### ISSUE TITLE
Vector methods are nil

### ISSUE THREAD

**Issue by GreenXenith** [bjornbytes/maf#6]
I was attempting to use this and kept getting a nil method error.
I ran the example provided in the README and got the same error.
```
lua: ./maf.lua:232: attempt to call method 'dot' (a nil value)
stack traceback:
	./maf.lua:232: in function <./maf.lua:231>
	(tail call): ?
	./test.lua:7: in main chunk
	[C]: ?
```
It seems the methods are inaccessible. Not that it is useful to me, but I figured out that the method can be accessed by doing `getmetatable(a).dot(a, b)`, which is of course terrible.

**Comment by bjornbytes** [comment]
The README example was a little outdated, it's fixed now.  Thanks!
